const URLS = {
  HOME: 'https://loja.electrolux.com.br/',
  CATEGORY: 'https://loja.electrolux.com.br/eletrodomesticos',
  PRODUCT:
    'https://loja.electrolux.com.br/lavadora-de-roupas-premium-care-11kg-front-load-electrolux-lfe11/p',
}

/** The `WORKSPACE` environment variable is generated by the workflow */
const WORKSPACE = process.env.WORKSPACE

function getUrls() {
  if (WORKSPACE) {
    return Object.values(URLS).map((url) => `${url}?workspace=${WORKSPACE}`)
  }

  return Object.values(URLS)
}

module.exports = {
  ci: {
    upload: {
      target: 'temporary-public-storage',
    },
    collect: {
      url: getUrls(),
      numberOfRuns: 1,
      settings: {
        chromeFlags:
          '--no-sandbox  --headless --disable-gpu --disable-dev-shm-usage',
      },
    },
    assert: {
      assertions: {
        'categories:performance': ['warning', { minScore: 0.3 }],
        'categories:accessibility': ['warning', { minScore: 0.7 }],
        'categories:best-practices': ['warning', { minScore: 0.7 }],
        'categories:seo': ['warning', { minScore: 0.8 }],
        'cumulative-layout-shift': ['warning', { maxNumericValue: 1 }],
        'errors-in-console': ['warning', { minScore: 0 }],
        'total-blocking-time': ['warning', { maxNumericValue: 3000 }],
        'first-contentful-paint': [
          'warning',
          { maxNumericValue: 4000, aggregationMethod: 'optimistic' },
        ],
        interactive: [
          'warning',
          { maxNumericValue: 5000, aggregationMethod: 'optimistic' },
        ],
      },
    },
  },
}
