name: Security

on:
  push:
    branches: [main, master, develop]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  security:
    name: Security
    uses: Electrolux-D2C/electrolux-actions/.github/workflows/security.yml@main
